version: '3.4'

services:
  postgresql-data:
    image: postgres:10
    environment:
      POSTGRES_PASSWORD: DigiMed123
    ports:
      - 5442:5432
    volumes:
      - postgres-data:/var/lib/postgresql/data

  api:
    image: docker.debugger.vn/api
    build:
      context: .
      dockerfile: Api/Dockerfile

  identity-api:
    image: docker.debugger.vn/identity-api
    build:
      context: .
      dockerfile: IdentityServerDemo/Dockerfile

volumes:
  postgres-data:
    external: true

