version: '3.4'

services:    
  postgresql-data:
    networks:
      - default

  api:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    networks:
      - default
    ports:
      - "5000:80"

  identity-api:
    environment:
      - Standalone=true
      - ASPNETCORE_ENVIRONMENT=Development
      - Logging__LogLevel__Default=Warning
    ports:
      - "5001:80"
    networks:
      - default
